### ISSUE TITLE
Error : in `require': no such file to load -- selenium-webdriver

### ISSUE THREAD

**Issue by crawler-IM** [openpreserve/pagelyzer#1]
Hi, 

Following the steps noted by you in the description : 

1)
$ ruby -v
ruby 1.9.2p290 (2011-07-09 revision 32553) [i686-linux]
$ gem -v
1.3.7 

2)
pagelyzer-ruby-0.9-standalone.zip downloaded and unzipped.

3)
Dependencies installed : 
$ sudo apt-get install libxslt-dev libxml2-dev 
$ sudo apt-get install openjdk-7-jdk 
$ sudo apt-get install imagemagick

4)
In the project folder : 
$ bundle
Fetching gem metadata from http://rubygems.org/.........
Fetching gem metadata from http://rubygems.org/..
Resolving dependencies...
Enter your password to install the bundled RubyGems to your system: 
Installing ffi (1.4.0) 
Installing childprocess (0.3.9) 
Installing hpricot (0.8.6) 
Installing multi_json (1.6.1) 
Installing nokogiri (1.5.5) 
Installing rubyzip (0.9.9) 
Installing sanitize (2.0.3) 
Installing websocket (1.0.7) 
Installing selenium-webdriver (2.29.0) 
Using bundler (1.3.2) 
Your bundle is complete! Use `bundle show [gemname]` to see where a bundled gem is installed.o gem install bundler

And a file "Gemfile.lock" was created.

5)
Running pagelyzer : 
After the dependencies were installed :
$ ./pagelyzer
USAGE: pagelyzer [--help|--version] [<command> <command_options>]

++++++++++++++++++++++++++++++++++++++++++++++

$ ./pagelyzer capture --url=http://google.fr
internal:lib/rubygems/custom_require:29:in `require': no such file to load -- selenium-webdriver (LoadError)
from <internal:lib/rubygems/custom_require>:29:in`require'
from /home/hatem/Bureau/travail/AD-658/pagelyzer-ruby-0.9-standalone/bin/pagelyzer_capture:36:in `<main>'

++++++++++++++++++++++++++++++++++++++++++++++

$ ./pagelyzer changedetection --url1=http://google.fr --url2=http://google.com
Using marcalizer.jar found in /home/hatem/Bureau/travail/AD-658/pagelyzer-ruby-0.9-standalone/ext/marcalizer
Notice: using 'firefox' as default browser
Pagelyzer: capturing URLhttp://google.com
internal:lib/rubygems/custom_require:29:in `require': no such file to load -- selenium-webdriver (LoadError)
from <internal:lib/rubygems/custom_require>:29:in`require'
from /home/hatem/Bureau/travail/AD-658/pagelyzer-ruby-0.9-standalone/bin/pagelyzer_capture:36:in `<main>'
<internal:lib/rubygems/custom_require>:29:in`require': no such file to load -- selenium-webdriver (LoadError)
from internal:lib/rubygems/custom_require:29:in `require'
from /home/hatem/Bureau/travail/AD-658/pagelyzer-ruby-0.9-standalone/bin/pagelyzer_capture:36:in`<main>'
cp: impossible d'évaluer «/home/hatem/Bureau/travail/AD-658/pagelyzer-ruby-0.9-standalone/out/firefox_google_fr.png»: Aucun fichier ou dossier de ce type
cp: impossible d'évaluer «/home/hatem/Bureau/travail/AD-658/pagelyzer-ruby-0.9-standalone/out/firefox_URLgoogle_com.png»: Aucun fichier ou dossier de ce type
Exception in thread "main" java.lang.UnsupportedClassVersionError: Taverna/ScapeTest : Unsupported major.minor version 51.0
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Could not find the main class: Taverna.ScapeTest. Program will exit. 

The error depends on the webdriver :
$ bundle show selenium-webdriver 
/usr/local/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.29.0

Am I missing somthing in the installation?

**Comment by asanoja** [comment]
May I have some extra information regarding the linux version used, I can not reproduce the error with a ubuntu 11.10 64bit. Also it helps to include the output of "gem -list" and "gem env" commands

**Comment by crawler-IM** [comment]
Hi,

I'm using Ubuntu 11.04 : 
$ uname -a
Linux hatem 2.6.38-8-generic #42-Ubuntu SMP Mon Apr 11 03:31:50 UTC 2011 i686 i686 i386 GNU/Linux
+++++++++++++++++++++++++++
$ gem env
RubyGems Environment:
- RUBYGEMS VERSION: 1.3.7
- RUBY VERSION: 1.9.2 (2011-07-09 patchlevel 290) [i686-linux]
- INSTALLATION DIRECTORY: /usr/local/lib/ruby/gems/1.9.1
- RUBY EXECUTABLE: /usr/local/bin/ruby
- EXECUTABLE DIRECTORY: /usr/local/bin
- RUBYGEMS PLATFORMS:
  - ruby
  - x86-linux
- GEM PATHS:
  - /usr/local/lib/ruby/gems/1.9.1
  - /home/hatem/.gem/ruby/1.9.1
- GEM CONFIGURATION:
  - :update_sources => true
  - :verbose => true
  - :benchmark => false
  - :backtrace => false
  - :bulk_threshold => 1000
- REMOTE SOURCES:
  - http://rubygems.org/  

+++++++++++++++++++++++++++

$ gem list

**\* LOCAL GEMS ***

bundler (1.3.2)
childprocess (0.3.9)
ffi (1.4.0)
hpricot (0.8.6)
minitest (1.6.0)
multi_json (1.6.1)
nokogiri (1.5.5)
rake (0.8.7)
rdoc (2.5.8)
rubyzip (0.9.9)
sanitize (2.0.3)
selenium-webdriver (2.29.0)
websocket (1.0.7)

Thanks.

**Comment by asanoja** [comment]
I still can not reproduce the error, but we can test installing the missing gem separately with:

sudo gem install selenium-webdriver

**Comment by crawler-IM** [comment]
$ sudo gem install selenium-webdriver
[sudo] password for hatem: 
Successfully installed selenium-webdriver-2.32.1
1 gem installed
Installing ri documentation for selenium-webdriver-2.32.1...
Installing RDoc documentation for selenium-webdriver-2.32.1...
$ ./pagelyzer capture --url=http://google.com
internal:lib/rubygems/custom_require:29:in `require': no such file to load -- selenium-webdriver (LoadError)
    from <internal:lib/rubygems/custom_require>:29:in`require'
    from /home/hatem/Bureau/travail/AD-658.1/pagelyzer-ruby-0.9-standalone/bin/pagelyzer_capture:36:in `<main>'

**Comment by asanoja** [comment]
Ok, I'll keep looking for a solution, it is strange but as soon as I can reproduce the error completely, I'll get back to you.

best

**Comment by asanoja** [comment]
Solved in the new version. Closing this issue
