### ISSUE TITLE
Dependency error in Debian package

### ISSUE THREAD

**Issue by crawler-IM** [openpreserve/pagelyzer#2]
Using the .deb package from:
http://deb.openplanetsfoundation.org/pool/main/p/pagelyzer-ruby/

When trying to install the Debian package on the IM cluster, we got the following dependency errors:

Selecting previously deselected package pagelyzer-ruby1.9.1.
(Reading database ... 207379 files and directories currently installed.)
Unpacking pagelyzer-ruby1.9.1 (from pagelyzer-ruby1.9.1_0.9-12-gbbcc12f_amd64.deb) ...
dpkg: dependency problems prevent configuration of pagelyzer-ruby1.9.1:
 pagelyzer-ruby1.9.1 depends on cdbs; however:
  Package cdbs is not installed.
 pagelyzer-ruby1.9.1 depends on ruby-pkg-tools; however:
  Package ruby-pkg-tools is not installed.
 pagelyzer-ruby1.9.1 depends on openjdk-6-jdk; however:
  Package openjdk-6-jdk is not installed.
dpkg: error processing pagelyzer-ruby1.9.1 (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db ...
Errors were encountered while processing:
 pagelyzer-ruby1.9.1

Note: The deb package is only available for 64bit systems. We therefore could not try it on a local machine (x86 system).

**Comment by asanoja** [comment]
Are you using the "dpkg -i" command?

if that is the case, it doesn't resolve dependencies. That is a limitation
of the deb platform. The suggested method, from dpkg documentation, is to
do:

sudo dpkg -i downloaded_package.deb
sudo apt-get -f install

best regards

On Wed, Mar 20, 2013 at 2:33 PM, crawler-IM notifications@github.comwrote:

> Using the .deb package from:
> http://deb.openplanetsfoundation.org/pool/main/p/pagelyzer-ruby/
> 
> When trying to install the Debian package on the IM cluster, we got the
> following dependency errors:
> 
> Selecting previously deselected package pagelyzer-ruby1.9.1.
> (Reading database ... 207379 files and directories currently installed.)
> Unpacking pagelyzer-ruby1.9.1 (from
> pagelyzer-ruby1.9.1_0.9-12-gbbcc12f_amd64.deb) ...
> dpkg: dependency problems prevent configuration of pagelyzer-ruby1.9.1:
> pagelyzer-ruby1.9.1 depends on cdbs; however:
> Package cdbs is not installed.
> pagelyzer-ruby1.9.1 depends on ruby-pkg-tools; however:
> Package ruby-pkg-tools is not installed.
> pagelyzer-ruby1.9.1 depends on openjdk-6-jdk; however:
> Package openjdk-6-jdk is not installed.
> dpkg: error processing pagelyzer-ruby1.9.1 (--install):
> dependency problems - leaving unconfigured
> Processing triggers for man-db ...
> Errors were encountered while processing:
> pagelyzer-ruby1.9.1
> 
> Note: The deb package is only available for 64bit systems. We therefore
> could not try it on a local machine (x86 system).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/openplanets/pagelyzer/issues/2
> .

## 

Andres Sanoja

LIP6 - UPMC. Paris. France
andres.sanoja@lip6.fr
Portable: 06 11 63  40 01

## 4 place Jussieu. 75005

Assistant Professor. Paralel and Distributed Computing Center.
Computing Department. Computing School.
Central University of Venezuela.
Caracas, Venezuela
Phone: + 58 212 6051323 Fax: + 58 81 6051134
E-mail1: afsanoja@gmail.com
E-mail2: andres.sanoja@ciens.ucv.ve
http://ccpd.ciens.ucv.ve/~asanoja

If you need to print this email or any attachments, reuse and recycle the
paper

**Comment by crawler-IM** [comment]
Hi Andrés,

Thanks for your response, it was helpful.
The installation is done.
