### ISSUE TITLE
Can pagelyzer run in a system without GUI?

### ISSUE THREAD

**Issue by crawler-IM** [openpreserve/pagelyzer#3]
We installed the debian package of pagelyzer in a system without a GUI.
3 commands are available now :
  1- pagelyzer_analyzer
  2- pagelyzer_changedetection
  3- pagelyzer_capture

We have 2 browsers on this machine : firefox and opera, in order to run them we use the X server Xvfb.

Trying to run pagelyzer : 

+++++++++++++++++++++++++++++
$ pagelyzer_capture --url=http://twitter.com 
Capturing http://twitter.com with local opera
Connection not possible with opera
WARNING: Is opera installed in your system?
Try with the --browser=your_installed_browser
USAGE: pagelyzer_capture --url=URL [--js_files_url=BASE_URL] [--output-folder=FOLDER] [--browser=BROWSER_CODE] [--thumbnail] [--help]
This tool aims to have a HTML document with the visual cues integrated, called Decorated HTML. This allows to save the state of a browser at the moment of capture
Browsers code are the same as defined in selenium. For instance:
- firefox
- chrome
- iexploreproxy
- safariproxy
- opera

Note: the browser should be installed in your machine to work with selenium webdriver

The output is sent to 'out' folder. If it doesn't exists it will be created
+++++++++++++++++++++++++++++

We ask if your tool can be runned on systems without a GUI.

Trying to run the browsers without a virtual display :
$ firefox 
Error: no display specified

$ opera
opera: cannot connect to X server . Error: No such device

**Comment by asanoja** [comment]
Hi,

It has not been tested under such requirements. It won't work for that configuration, for the time being.

regards

**Comment by crawler-IM** [comment]
Hi,

I think we solved this problem differently :

Instead of changing the source code of pagelyzer to call firefox (or any other browser) in an XServer, we can run pagelyzer in a virtual display from the beginning :

$ DISPLAY=:1 xvfb-run pagelyzer_changedetection --url1=http://maps.google.com --url2=http://google.com --output-folder=./
Using marcalizer.jar found in /home/crawl/pagelyzer/marcalizer
Notice: using 'firefox' as default browser
Capturing http://maps.google.com with local firefox
Waiting page to finish loading... (Timeout in 10sec)
Browser closed
done.
Capturing http://google.com with local firefox
Waiting page to finish loading... (Timeout in 10sec)
Browser closed
done.
SIFT Computation...
BOW Computation...
Visual Features Computation...
Classification...
0.37208013647619376

Thanks.

**Comment by asanoja** [comment]
The headless mode for pagelyzer it is now in the new version with the --headless parameter. There will be no need to do it explicity like have you done before.

best,
