### ISSUE TITLE
Connection not possible with firefox

### ISSUE THREAD

**Issue by martinklein0815** [openpreserve/pagelyzer#7]
Hi,

I have installed pagelyzer and all its dependencies but the software does not use/find my installed Firefox instance.
When I run:

./pagelyzer capture --url=http://www.cnn.com

nothing happens for ca. 60 seconds and then it seems to time out with:

Connection not possible with firefox
WARNING: Is firefox installed in your system?
Try with the --browser=your_installed_browser
unable to obtain stable firefox connection in 60 seconds (127.0.0.1:7055)

followed by the regular output about usage etc.
Any help is much appreciated.

The parameters of my system:

$ uname -a
Linux abacus 2.6.38-11-generic #50-Ubuntu SMP Mon Sep 12 21:17:25 UTC 2011 x86_64 x86_64 x86_64 GNU/Linux

$ ruby -v
ruby 1.9.2p290 (2011-07-09 revision 32553) [x86_64-linux]

$ gem -v
1.3.7

$ gem env
RubyGems Environment:
- RUBYGEMS VERSION: 1.3.7
- RUBY VERSION: 1.9.2 (2011-07-09 patchlevel 290) [x86_64-linux]
- INSTALLATION DIRECTORY: /usr/local/bin/ruby-1.9.2-p290/lib/ruby/gems/1.9.1
- RUBY EXECUTABLE: /usr/local/bin/ruby-1.9.2-p290/bin/ruby
- EXECUTABLE DIRECTORY: /usr/local/bin/ruby-1.9.2-p290/bin
- RUBYGEMS PLATFORMS:
  - ruby
  - x86_64-linux
- GEM PATHS:
  - /usr/local/bin/ruby-1.9.2-p290/lib/ruby/gems/1.9.1
  - /home/mklein/.gem/ruby/1.9.1
- GEM CONFIGURATION:
  - :update_sources => true
  - :verbose => true
  - :benchmark => false
  - :backtrace => false
  - :bulk_threshold => 1000
- REMOTE SOURCES:
  - http://rubygems.org/

$ gem list

**\* LOCAL GEMS ***

bundler (1.3.5)
childprocess (0.3.9)
ffi (1.9.0)
headless (1.0.1)
mini_magick (3.6.0)
mini_portile (0.5.1)
minitest (1.6.0)
multi_json (1.8.1)
nokogiri (1.6.0)
rake (0.8.7)
rdoc (2.5.8)
rjb (1.4.8)
rubyzip (0.9.9)
sanitize (2.0.6)
selenium-webdriver (2.35.1)
subexec (0.2.3)
websocket (1.0.7)

$ bundle show
Gems included by the bundle:
- bundler (1.3.5)
- childprocess (0.3.9)
- ffi (1.9.0)
- headless (1.0.1)
- mini_magick (3.6.0)
- mini_portile (0.5.1)
- multi_json (1.8.1)
- nokogiri (1.6.0)
- rjb (1.4.8)
- rubyzip (0.9.9)
- sanitize (2.0.6)
- selenium-webdriver (2.35.1)
- subexec (0.2.3)
- websocket (1.0.7)

$ which firefox
/usr/bin/firefox

$ firefox -v
Mozilla Firefox 24.0

**Comment by asanoja** [comment]
Hi,

Can you please check that the firefox path is correct in the file "lib/pagelyzer_capture.rb" line 37. Where it says:

Selenium::WebDriver::Firefox::Binary.path='/usr/bin/firefox'

Sometimes, it is referred as firefox-bin.

We have two options:
1. Change it explicity (explained above)
2. Comment this line and let the webdriver decide

If it do not work please do not hesitate to write

best regards

andrés

**Comment by martinklein0815** [comment]
The path was correct. The issue was with my X environment, I didn't expect the browser window to open but thought it would run in the background. Once solved, it works fine. 
Thx!

M
